# Make sure to check the documentation at http://goreleaser.com

before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - github:
      owner: mightymatth
      name: arcli
    homepage: https://github.com/mightymatth/arcli
    description: "Awesome Redmine CLI"
    install: |-
      bin.install "arcli"
      bash_completion.install "completions/arcli.bash" => "arcli"
      zsh_completion.install "completions/arcli.zsh" => "_arcli
      fish_completion.install "completions/arcli.fish"
    test: |
      system "#{bin}/arcli --version"

snapcrafts:
  - summary: Awesome Redmine CLI
    publish: true # <- this line
    description: |
      CLI tool that makes Redmine awesome
    grade: stable
    confinement: strict
    license: MIT
    apps:
      arcli:
        plugs: ["home", "network"]
